### ISSUE TITLE
Android crash(NullPointerException) in 9.1.0

### ISSUE THREAD

**Issue by Xmilton** [AppLovin/Android-SDK-Demo#36]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.applovin.impl.sdk.c.d.e(long)' on a null object reference
       at com.applovin.impl.adview.k$21.onPrepared(Unknown Source)
       at android.widget.VideoView$2.onPrepared(VideoView.java:535)
       at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3114)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:210)
       at android.app.ActivityThread.main(ActivityThread.java:5988)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:852)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:742)
Please Fix the crash

**Comment by santoshbagadi** [comment]
Hi, thank you for reporting the issue. We found the cause of the issue and we will be adding the fix in our next release.

**Comment by Xmilton** [comment]
OK,thanks.

**Comment by thomasmso** [comment]
@Xmilton - We have released an [Android SDK](https://bintray.com/applovin/Android/sdk_android/9.1.3) with these NPE fixes. Thank you once again for reporting it!
