### ISSUE TITLE
crash on Android 5

### ISSUE THREAD

**Issue by OlegTarashkevich** [AppLovin/Android-SDK-Demo#61]
Hi,

 @tiandrew @thomasmso

I updated:
1. The sdk from 9.12.3 to 9.12.6
2. Third-party library "androidx.appcompat:appcompat:$v" from 1.0.2 to .1.1.0

And now the app crashes on Android 5. Looks like a problem with webView.
I also use webView in the app and it crashed. Then I found the following solution: https://stackoverflow.com/a/58355733/2946353 and set all the Activities on android: configChanges = "uiMode". The crash disappeared from my code, but sdk continues to crash the app.

I found this crash in crashlytics.

What to do?

`Fatal Exception: android.content.res.Resources$NotFoundException: String resource ID #0x3040005
       at android.content.res.HwResources.getText(HwResources.java:1299)
       at android.content.res.Resources.getString(Resources.java:398)
       at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:733)
       at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:657)
       at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:649)
       at com.android.org.chromium.android_webview.AwContents.setNewAwContents(AwContents.java:798)
       at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:634)
       at com.android.org.chromium.android_webview.AwContents.<init>(AwContents.java:571)
       at com.android.webview.chromium.WebViewChromium.initForReal(WebViewChromium.java:332)
       at com.android.webview.chromium.WebViewChromium.access$100(WebViewChromium.java:102)
       at com.android.webview.chromium.WebViewChromium$1.run(WebViewChromium.java:284)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.drainQueue(WebViewChromium.java:129)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue$1.run(WebViewChromium.java:116)
       at com.android.org.chromium.base.ThreadUtils.runOnUiThread(ThreadUtils.java:144)
       at com.android.webview.chromium.WebViewChromium$WebViewChromiumRunQueue.addTask(WebViewChromium.java:113)
       at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:281)
       at android.webkit.WebView.<init>(WebView.java:577)
       at android.webkit.WebView.<init>(WebView.java:512)
       at android.webkit.WebView.<init>(WebView.java:495)
       at android.webkit.WebView.<init>(WebView.java:482)
       at android.webkit.WebView.<init>(WebView.java:472)
       at com.applovin.impl.adview.g.<init>(g.java)
       at com.applovin.impl.adview.c.<init>(c.java)
       at com.applovin.impl.adview.c.<init>(c.java)
       at com.applovin.impl.adview.c.a(c.java)
       at com.applovin.impl.adview.AdViewControllerImpl.attachNewAdView(AdViewControllerImpl.java)
       at com.applovin.impl.adview.AdViewControllerImpl.a(AdViewControllerImpl.java)
       at com.applovin.impl.adview.AdViewControllerImpl.initializeAdView(AdViewControllerImpl.java)
       at com.applovin.adview.AppLovinAdView.a(AppLovinAdView.java)
       at com.applovin.adview.AppLovinAdView.<init>(AppLovinAdView.java)
       at com.prilaga.ads.banner.AppLovinBanner.show(AppLovinBanner.java:39)
       at com.prilaga.ads.banner.BannerAds.showNextAdFromQueue(BannerAds.java:297)
       at com.prilaga.ads.banner.BannerAds$1.requestForNewAd(BannerAds.java:51)
       at com.prilaga.ads.banner.YandexBanner$1$2.run(YandexBanner.java:70)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5569)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:726)`

**Comment by thomasmso** [comment]
Hi @OlegTarashkevich, thanks for reporting the issue (and the fix) - we'll implement it accordingly in the next SDK release and will update this thread.

**Comment by thomasmso** [comment]
The fix has been released in Android SDK v9.12.7.
