### ISSUE TITLE
Setting SdkKey programmatically not working

### ISSUE THREAD

**Issue by mohamad62** [AppLovin/Android-SDK-Demo#65]
When I use this method I get an error that says the sdkkey is not correct:

final AppLovinSdk appLovinSdk = AppLovinSdk.getInstance( "EGHL5i8CTBb78Dg_KK0XH642hCJ4umqDp4SMZfBUTT66OaufwPFB-1q__u_4fKudyGwb6HBxewIE4M7IvikP9R", new AppLovinSdkSettings( this ), this );

But when I use the sdkkey in the manifest everything is ok, could you please help m

**Comment by thomasmso** [comment]
What's the exact error you're seeing?

**Comment by mohamad62** [comment]
2020-10-29 10:03:35.270 1662-1662/? E/AppLovinSdk: [AppLovinSdk] Called with an invalid SDK key from: java.lang.Throwable: 
        at com.applovin.impl.sdk.k.a(Unknown Source:394)
        at com.applovin.sdk.AppLovinSdk.a(Unknown Source:105)
        at com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:1)
        at com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:14)
        at com.applovin.sdk.AppLovinSdk.getInstance(Unknown Source:5)
        at com.applovin.sdk.AppLovinSdk.initializeSdk(Unknown Source:2)
        at com.applovin.sdk.AppLovinSdk.initializeSdk(Unknown Source:1)
        at org.telegram.messenger.ApplicationLoader$3.onActivateComplete(ApplicationLoader.java:251)

**Comment by thomasmso** [comment]
That should only be called if you're using our SDK via `AppLovinSdk.getInstance( context );` without having an SDK key in the Android Manifest. Are you able to reproduce in this demo app? If so could you zip and send the project?

**Comment by mohamad62** [comment]
Nothing happens when I don't have an sdk key in the manifest, is there any older version that supports this feature?

**Comment by thomasmso** [comment]
All SDKs should support the feature - anytime you access the SDK, you need to pass in the SDK key using `AppLovinSdk sdk = AppLovinSdk.getInstance( "sdk_key_here", ...)`. When integrating our ads, you need to pass in the instance of the `sdk` into the constructors as well.

**Comment by mohamad62** [comment]
I tried a lot but I couldn't solve the problem, I think it's a bug, Some users have already reported this bug too

**Comment by thomasmso** [comment]
Can you send me your integration code? thomas.so@applovin.com
